### ISSUE TITLE
Spriting

### ISSUE THREAD

**Issue by OnyxSteel** [rylid-umil/New-Units#10]
Seeing as most units are without a sprite, I assume you need sprites.
Do you mind if I sprite for you? My discord is Aegires#8763 if you wish to make contact with me.

**Comment by rylid-umil** [comment]
Yes please! im not the best spriter so I'd really appreciate any help. Many don't have sprites because i haven't made their sprite yet or they got removed so i didn't get blacklisted from using another mod's sprites
