### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by wesley306** [rylid-umil/New-Units#15]
wanted to know how do I create new units?

**Comment by wesley306** [comment]
wanted to know if you are still working on the mod and there will also be a unit manufacturer for the new units?

**Comment by wesley306** [comment]
I wanted to know what problem you are going through finishing the mod?

**Comment by rylid-umil** [comment]
Sorry, but mod moved to Chaoticans-mindustry-modding-team/New-Content. look up some tutorials online for how to mod and make enw units. development here stopped. yes, i will add unit factories for new units, but only in the new repo.
