### ISSUE TITLE
Mate, you're an id**t

### ISSUE THREAD

**Issue by stacktrace-error** [rylid-umil/New-Units#2]
First of all, the browser is based on the mindustry-mod tag that *you* have to add to the repo.

Second, literally any MS paint drawing would have been better used as sprites since taking sprites without permission results in a permanent blacklisting of your mod from the browser, making it effectively dead, forever.

If you'd like to start *properly* modding join the mindustry discord and talk to us in the modding channels, we're (mostly) happy to help.

**Comment by rylid-umil** [comment]
i will remove them but i will jsut replace them with ohno

**Comment by rylid-umil** [comment]
im not fixixng them and do not call people ididots, if people complain about ohno's its your's and aureostratus's fault

**Comment by rylid-umil** [comment]
it says im banned from the mindustry discord server guild, but i dont remember why i was banned or even being banned at all
